name: Update Top Languages Badge
on:
  schedule:
    - cron: '0 0 * * *' # Tous les jours à minuit

jobs:
  update-badge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Update README
        run: |
          curl -o README.md https://raw.githubusercontent.com/Josh012006/Josh012006/main/README.md
          git add README.md
          git commit -m "Update Top Languages Badge [skip ci]"
          git push

